# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
	use_frameworks!

target 'MadeInWebYouTube' do
    pod 'Alamofire'
    pod 'ObjectMapper'
    pod 'AlamofireObjectMapper'

  # Pods for MadeInWebYouTube

  target 'MadeInWebYouTubeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
